spring:
  application:
    name: springboot-gateway

eureka:
  client:
    service-url:
     defaultZone: http://wsb:wsb@localhost:8080/eureka/ 
    registry-fetch-interval-seconds: 5 
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5  
    lease-expiration-duration-in-seconds: 10 

server:
  port: 8083
zuul:
  routes:
    springboot-server:
        path: /springboot-server/**
        sensitiveHeaders:
        serviceId: springboot-server
    springboot-server1:
        path: /springboot-server1/**
        sensitiveHeaders:
        serviceId: springboot-server1
  add-proxy-headers: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

logging:
  level:
    com.app: debug

#ribbon配置时长，处理超时
ribbon:
  eureka:
    enabled: true
  hystrix:
    enabled: true
  ConnectTimeout: 20000
  ReadTimeout: 20000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 3
  MaxAutoRetries: 3

#feign:
#  hystrix:
#    enabled: true
#  client:
#    config:
#      default:
#        connectTimeout: 2000
#        readTimeout: 2000
