server:
  port: 8080


eureka:
  client:
    service-url:
     defaultZone: http://wsb:wsb@localhost:8080/eureka/
    fetch-registry: false
    register-with-eureka: false
    eureka-service-url-poll-interval-seconds: 60
  server:
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false
    use-read-only-response-cache: false
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

spring:
  application:
    name: springboot-eureka


logging:
  level:
    com.app: debug


#ribbon配置时长，处理超时
ribbon:
  eureka:
    enabled: true
  hystrix:
    enabled: true
  ConnectTimeout: 20000
  ReadTimeout: 20000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 3
  MaxAutoRetries: 3